# Generated by Django 5.0.3 on 2024-04-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savvyfoods", "0005_junks_restaurant"),
    ]

    operations = [
        migrations.AddField(
            model_name="foods",
            name="name",
            field=models.CharField(default="Rice and Chicken", max_length=100),
        ),
        migrations.AddField(
            model_name="junks",
            name="name",
            field=models.CharField(default="Beef", max_length=100),
        ),
    ]
