# Generated by Django 5.0.3 on 2024-04-21 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "savvyfoods",
            "0007_remove_cart_order_alter_cart_user_alter_foods_name_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="foods",
            old_name="deliverytime",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="junks",
            old_name="deliverytime",
            new_name="availability",
        ),
        migrations.RemoveField(
            model_name="junks",
            name="description",
        ),
        migrations.AddField(
            model_name="junks",
            name="category",
            field=models.CharField(default="rice", max_length=20),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="closing_hour",
            field=models.TimeField(
                default=datetime.datetime(2024, 4, 21, 14, 50, 45, 919034)
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="opening_hour",
            field=models.TimeField(
                default=datetime.datetime(2024, 4, 21, 14, 50, 45, 919034)
            ),
        ),
    ]
