# Generated by Django 5.0.3 on 2024-04-22 08:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savvyfoods", "0008_rename_deliverytime_foods_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="food",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="junk",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="restaurant",
        ),
        migrations.AlterField(
            model_name="junks",
            name="category",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="closing_hour",
            field=models.TimeField(
                default=datetime.datetime(2024, 4, 22, 9, 47, 47, 169932)
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="opening_hour",
            field=models.TimeField(
                default=datetime.datetime(2024, 4, 22, 9, 47, 47, 169932)
            ),
        ),
        migrations.CreateModel(
            name="Referal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("point", models.IntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
