# Generated by Django 5.0.3 on 2024-04-22 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savvyfoods", "0009_remove_cartitem_food_remove_cartitem_junk_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foods",
            name="contents",
        ),
        migrations.RemoveField(
            model_name="junks",
            name="junk",
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="closing_hour",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="opening_hour",
            field=models.TimeField(),
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="foods")),
                ("contents", models.CharField(max_length=100)),
                ("rating", models.IntegerField()),
                ("deliveryfee", models.IntegerField()),
                ("category", models.CharField(max_length=20)),
                ("price", models.IntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
