# Generated by Django 5.0.3 on 2024-04-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("savvyfoods", "0011_alter_cart_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="contents",
        ),
    ]
