# Generated by Django 5.0.3 on 2024-05-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savvyfoods", "0014_alter_cart_image_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivered",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Referal",
        ),
    ]
