# Generated by Django 5.0.3 on 2024-05-07 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_profile_phone"),
        ("savvyfoods", "0016_advert"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="category",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivered",
        ),
        migrations.RemoveField(
            model_name="order",
            name="deliveryfee",
        ),
        migrations.RemoveField(
            model_name="order",
            name="image",
        ),
        migrations.RemoveField(
            model_name="order",
            name="name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="price",
        ),
        migrations.RemoveField(
            model_name="order",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="order",
            name="rating",
        ),
        migrations.AddField(
            model_name="order",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.profile",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="real_food",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="savvyfoods.foods",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="real_junk",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="savvyfoods.junks",
            ),
        ),
    ]
