# Generated by Django 5.0.3 on 2024-05-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savvyfoods", "0017_remove_order_category_remove_order_delivered_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivered",
            field=models.BooleanField(null=True, verbose_name=False),
        ),
    ]
