# Generated by Django 5.0.3 on 2024-05-14 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savvyfoods", "0018_order_delivered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivered",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="real_food",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="savvyfoods.foods",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="real_junk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="savvyfoods.junks",
            ),
        ),
    ]
